// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz5Z5QiKviNlNxezRMHC1JbST44VoALbY',
    appId: '1:408470968846:web:d4ea2335af9729b19ffa5f',
    messagingSenderId: '408470968846',
    projectId: 'all-products-af6de',
    authDomain: 'all-products-af6de.firebaseapp.com',
    databaseURL: 'https://all-products-af6de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'all-products-af6de.appspot.com',
    measurementId: 'G-2Q25SJ59Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAryDEj2ajWdZp0DjNmLg3fAw2V3rfq7to',
    appId: '1:408470968846:android:d6117def227d50169ffa5f',
    messagingSenderId: '408470968846',
    projectId: 'all-products-af6de',
    databaseURL: 'https://all-products-af6de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'all-products-af6de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqiWrnhMIse-qWUh908hyhel13wXn5vJ4',
    appId: '1:408470968846:ios:de31f34b7b147f379ffa5f',
    messagingSenderId: '408470968846',
    projectId: 'all-products-af6de',
    databaseURL: 'https://all-products-af6de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'all-products-af6de.appspot.com',
    androidClientId: '408470968846-5mbfvfmp89730falqfa1cpjckfo7k7el.apps.googleusercontent.com',
    iosClientId: '408470968846-h5er1qn79papfn0gllvan9c5rv08derq.apps.googleusercontent.com',
    iosBundleId: 'com.cnvfirj.trening',
  );
}
